### ISSUE TITLE
help please !

### ISSUE THREAD

**Issue by YousseMes** [dm8tbr/org.eclipse.paho.mqtt.python#1]
I am a beginner for mqtt !
And the examples that you have done help me to learn programming with pytthon
so now i can make some pub&sub but i have a problème
if i receive data from some publisher i want make publish automatically
for example if a receive "on" from topic1 send "off" to topic2
please thear's no example for that hope you can help me thank you .

**Comment by dm8tbr** [comment]
If you haven't figured this out by now. This is a *fork* of the Apache Paho Python repository. I'm not the maintainer of it. I only introduced a small Mer/IPHB specific patch. I'd suggest to look at the upstream Apache project, if you haven't yet.

Unfortunately I can not offer general training and Q&A on MQTT.
